name: Build, Push to ECR & Update GitOps Repo

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/workflows/**"

permissions:
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 208851973471.dkr.ecr.us-east-1.amazonaws.com

  FRONTEND_REPOSITORY: inventory-frontend
  BACKEND_REPOSITORY: inventory-backend

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Application Repository
        uses: actions/checkout@v4

      ####################################################
      # Configure AWS
      ####################################################

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      ####################################################
      # Login to Amazon ECR
      ####################################################

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      ####################################################
      # Generate Image Tag
      ####################################################

      - name: Generate Image Tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      ####################################################
      # Build Backend
      ####################################################

      - name: Build Backend Docker Image
        run: |
          docker build \
          -t $ECR_REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG \
          -t $ECR_REGISTRY/$BACKEND_REPOSITORY:latest \
          ./backend

      ####################################################
      # Push Backend
      ####################################################

      - name: Push Backend Docker Image
        run: |
          docker push $ECR_REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$BACKEND_REPOSITORY:latest

      ####################################################
      # Build Frontend
      ####################################################

      - name: Build Frontend Docker Image
        run: |
          docker build \
          -t $ECR_REGISTRY/$FRONTEND_REPOSITORY:$IMAGE_TAG \
          -t $ECR_REGISTRY/$FRONTEND_REPOSITORY:latest \
          ./frontend

      ####################################################
      # Push Frontend
      ####################################################

      - name: Push Frontend Docker Image
        run: |
          docker push $ECR_REGISTRY/$FRONTEND_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$FRONTEND_REPOSITORY:latest

      ####################################################
      # Clone GitOps Repository
      ####################################################

      - name: Clone GitOps Repository
        run: |
          git clone https://${{ secrets.GITOPS_PAT }}@github.com/Dharunr257/enterprise-gitops.git

      ####################################################
      # Update Helm values.yaml
      ####################################################

      - name: Update Image Tags
        run: |

          sed -i "s/tag: .*/tag: ${IMAGE_TAG}/" \
          enterprise-gitops/inventory-app-helm/values.yaml

      ####################################################
      # Commit Changes
      ####################################################

      - name: Commit Changes
        run: |

          cd enterprise-gitops

          git config user.name "github-actions"

          git config user.email "github-actions@github.com"

          git add inventory-app-helm/values.yaml

          git diff --cached --quiet || git commit -m "Update images to ${IMAGE_TAG}"

          git push
