name: Build, Push to ECR & Update GitOps Repo

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/workflows/**"
      - "Dockerfile.backend"
      - "Dockerfile.frontend"

permissions:
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 208851973471.dkr.ecr.us-east-1.amazonaws.com

  FRONTEND_REPOSITORY: inventory-frontend
  BACKEND_REPOSITORY: inventory-backend

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      ####################################################
      # Checkout Application Repository
      ####################################################

      - name: Checkout Application Repository
        uses: actions/checkout@v4

      ####################################################
      # Configure AWS Credentials
      ####################################################

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      ####################################################
      # Login to Amazon ECR
      ####################################################

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      ####################################################
      # Generate Image Tag
      ####################################################

      - name: Generate Image Tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      ####################################################
      # Build Backend Image
      ####################################################

      - name: Build Backend Docker Image
        run: |
          docker build \
            -f Dockerfile.backend \
            -t $ECR_REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$BACKEND_REPOSITORY:latest \
            .

      ####################################################
      # Push Backend Image
      ####################################################

      - name: Push Backend Docker Image
        run: |
          docker push $ECR_REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$BACKEND_REPOSITORY:latest

      ####################################################
      # Build Frontend Image
      ####################################################

      - name: Build Frontend Docker Image
        run: |
          docker build \
            -f Dockerfile.frontend \
            -t $ECR_REGISTRY/$FRONTEND_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$FRONTEND_REPOSITORY:latest \
            .

      ####################################################
      # Push Frontend Image
      ####################################################

      - name: Push Frontend Docker Image
        run: |
          docker push $ECR_REGISTRY/$FRONTEND_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$FRONTEND_REPOSITORY:latest

      ####################################################
      # Clone GitOps Repository
      ####################################################

      - name: Clone GitOps Repository
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/Dharunr257/enterprise-gitops.git

      ####################################################
      # Install yq
      ####################################################

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      ####################################################
      # Update Helm values.yaml
      ####################################################

      - name: Update Helm Image Tags
        run: |

          yq -i '
          .frontend.image.tag = env(IMAGE_TAG) |
          .backend.image.tag = env(IMAGE_TAG)
          ' enterprise-gitops/inventory-app-helm/values.yaml

      ####################################################
      # Commit Changes
      ####################################################

      - name: Commit and Push GitOps Changes
        run: |

          cd enterprise-gitops

          git config user.name "github-actions"

          git config user.email "github-actions@github.com"

          git add inventory-app-helm/values.yaml

          if git diff --cached --quiet; then
            echo "No changes detected."
            exit 0
          fi

          git commit -m "Update inventory application image to ${IMAGE_TAG}"

          git push